"""cria investments e investment_assets

- `investment_assets` e catalogo **global**, nao por usuario: a cotacao da PETR4
  e publica, e uma linha por dono faria o agendador bater na BRAPI uma vez por
  usuario do mesmo papel. O indice unico compara `upper(symbol)` para que
  "petr4" e "PETR4" nao convivam como dois ativos.
- `investments.asset_id` sem `ondelete`: o catalogo nao e excluido pela API, e
  NO ACTION garante que uma limpeza futura nao leve junto a posicao de ninguem.
- Os CHECK sao simples de proposito. A regra cruzada ("renda variavel exige
  ativo, renda fixa exige indice") e do servico, onde a recusa sai como 422 com
  o campo apontado em vez de 500 na violacao de constraint.
- `transactions.investment_id` com `SET NULL`: excluir a posicao nao apaga o
  aporte que saiu da conta nem o provento que entrou. Parcial porque a
  esmagadora maioria dos lancamentos nao tem investimento.

Revision ID: 3843a0cc184a
Revises: 5d28986187b0
Create Date: 2026-09-18 10:35:18.089282
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3843a0cc184a"
down_revision: str | None = "5d28986187b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investment_assets",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "br_stock",
                "us_stock",
                "crypto",
                "cdb",
                "lci",
                "treasury",
                "savings",
                name="investment_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("previous_close", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("change_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('br_stock', 'crypto', 'us_stock')",
            name=op.f("ck_investment_assets_variable_income_only"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investment_assets")),
    )
    op.create_index(
        "ix_investment_assets_quoted_at", "investment_assets", ["quoted_at"], unique=False
    )
    op.create_index(
        "uq_investment_assets_type_symbol",
        "investment_assets",
        ["type", sa.literal_column("upper(symbol)")],
        unique=True,
    )
    op.create_table(
        "investments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "br_stock",
                "us_stock",
                "crypto",
                "cdb",
                "lci",
                "treasury",
                "savings",
                name="investment_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("average_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column(
            "invested_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "rate_index",
            sa.Enum(
                "cdi",
                "selic",
                "ipca",
                "savings",
                "prefixed",
                name="rate_index",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("rate_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("applied_on", sa.Date(), nullable=True),
        sa.Column("matures_on", sa.Date(), nullable=True),
        sa.Column(
            "current_value",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("value_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "average_price IS NULL OR average_price >= 0",
            name=op.f("ck_investments_average_price_not_negative"),
        ),
        sa.CheckConstraint(
            "current_value >= 0", name=op.f("ck_investments_current_value_not_negative")
        ),
        sa.CheckConstraint(
            "invested_amount >= 0", name=op.f("ck_investments_invested_amount_not_negative")
        ),
        sa.CheckConstraint(
            "matures_on IS NULL OR applied_on IS NULL OR matures_on >= applied_on",
            name=op.f("ck_investments_matures_after_applied"),
        ),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity >= 0", name=op.f("ck_investments_quantity_not_negative")
        ),
        sa.CheckConstraint(
            "rate_percent IS NULL OR rate_percent > 0",
            name=op.f("ck_investments_rate_percent_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["investment_assets.id"],
            name=op.f("fk_investments_asset_id_investment_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_investments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investments")),
    )
    op.create_index("ix_investments_asset_id", "investments", ["asset_id"], unique=False)
    op.create_index(
        "ix_investments_rate_index",
        "investments",
        ["rate_index"],
        unique=False,
        postgresql_where=sa.text("rate_index IS NOT NULL"),
        sqlite_where=sa.text("rate_index IS NOT NULL"),
    )
    op.create_index("ix_investments_user_id", "investments", ["user_id"], unique=False)
    op.add_column("transactions", sa.Column("investment_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_transactions_investment_id",
        "transactions",
        ["investment_id"],
        unique=False,
        postgresql_where=sa.text("investment_id IS NOT NULL"),
        sqlite_where=sa.text("investment_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_transactions_investment_id_investments"),
        "transactions",
        "investments",
        ["investment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transactions_investment_id_investments"), "transactions", type_="foreignkey"
    )
    op.drop_index(
        "ix_transactions_investment_id",
        table_name="transactions",
        postgresql_where=sa.text("investment_id IS NOT NULL"),
        sqlite_where=sa.text("investment_id IS NOT NULL"),
    )
    op.drop_column("transactions", "investment_id")
    op.drop_index("ix_investments_user_id", table_name="investments")
    op.drop_index(
        "ix_investments_rate_index",
        table_name="investments",
        postgresql_where=sa.text("rate_index IS NOT NULL"),
        sqlite_where=sa.text("rate_index IS NOT NULL"),
    )
    op.drop_index("ix_investments_asset_id", table_name="investments")
    op.drop_table("investments")
    op.drop_index("uq_investment_assets_type_symbol", table_name="investment_assets")
    op.drop_index("ix_investment_assets_quoted_at", table_name="investment_assets")
    op.drop_table("investment_assets")
    # ### end Alembic commands ###
