"""cria investment_rates

Cache dos indices do Banco Central que avaliam a renda fixa. Entra porque a
BRAPI fechou CDI, SELIC e IPCA atras do plano pago; a API SGS e publica.

- **O indice e a chave primaria.** Existe uma linha por indice, e ela vale a
  ultima leitura — o agendador grava por `merge`, sem id sintetico a consultar.
- `annual_percent` ja e **anualizado**: duas series vem em % ao dia util e duas
  em % ao mes, e converter na leitura (`providers.bcb.annualize`) e o que
  permite a um calculo so avaliar as quatro modalidades.
- `reference_date` nao e `fetched_at`: o SGS publica com atraso, e um CDI de
  ontem e dado correto. Guardar so a hora da busca faria a tela dizer
  "atualizado agora" sobre um numero de tres dias atras.
- Sem linha para `prefixed`: a taxa dele e a contratada na propria posicao, e
  nao ha indice a consultar. O enum e compartilhado com `investments.rate_index`.

Revision ID: f6f7100166fa
Revises: 3843a0cc184a
Create Date: 2026-09-18 11:25:56.903687
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f6f7100166fa"
down_revision: str | None = "3843a0cc184a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investment_rates",
        sa.Column(
            "index",
            sa.Enum(
                "cdi",
                "selic",
                "ipca",
                "savings",
                "prefixed",
                name="rate_index",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("annual_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("index", name=op.f("pk_investment_rates")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("investment_rates")
    # ### end Alembic commands ###
